Faisal/pkg resources update
openedx/openedx-tutor-plugins pull request #30
Opened 2024-10-01 07:26 UTC by beingfaisal

Tickets
- [Drop Python 3.8 & Add Support for Python 3.12](https://github.com/openedx/openedx-tutor-plugins/issues/27)
- [Move on from deprecated pkg_resources api](https://github.com/openedx/openedx-tutor-plugins/issues/26)

Action Items
- replaces pkg_resources api from importlib_resources api
- drops support for python 3.8 and add support for python 3.11 & python 3.12

2024-10-01 08:18 UTC, farhan requested changes

2024-10-01 08:18 UTC, farhan commented on plugins/tutor-contrib-learner-dashboard-mfe/tutor_learner_dashboard_mfe/__about__.py
> +__version__ = "0.1.2"
"0.2.0" as we are dropping python version supports and its less than 1.0

2024-10-03 07:16 UTC, farhan approved these changes

2024-10-25 16:26 UTC, feanil approved these changes

2024-10-25 16:26 UTC, merged